Solace/6.11: Fix merge conflict: show_mem()
arch/x86/kernel/nmi.c: In function ‘unknown_nmi_error’:
arch/x86/kernel/nmi.c:312:2: error: too many arguments to function
‘show_mem’
  show_mem(0,NULL);